### ISSUE TITLE
Elasticsearch is not present

### ISSUE THREAD

**Issue by Truth1984** [theasp/docker-fluentd-plugins#1]
https://github.com/uken/fluent-plugin-elasticsearch

it is not an Obsoleted plugin

using

`docker run --rm -it theasp/fluentd-plugins:slim cat /plugins-installed | grep elasticsearch`

only returns

`fluent-plugin-elasticsearch-timestamp-check (0.3.0)`

**Comment by Truth1984** [comment]
Your ruby version is `ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]`

but `elasticsearch-api requires Ruby version >= 2.4.`

**Comment by Truth1984** [comment]
You may want to try

```
FROM fluent/fluentd:edge-debian
COPY build.bash /build.bash
USER root
RUN apt-get update && apt-get install -qy bash && /build.bash certified
USER fluent
```

for `Dockerfile-certified`

**Comment by theasp** [comment]
Hi @Truth1984, thanks!  I've added new tags for `edge-certified`, `edge-slim` and `edge-common`.
